Repository Activiti/activiti-cloud-query, pull requests merged in 2018-12, with the labels that each got.

#53 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.96
  pom.xml
Labels: in progress, updatebot

#56 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.100
  pom.xml
Labels: in progress, updatebot

#57 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.104
  pom.xml
Labels: in progress, updatebot

#60 Pr/54
  .dockerignore
  .gitignore
  .helmignore
  .mergify.yml
  .updatebot.yml
  Dockerfile
  Jenkinsfile
  Jenkinsfile.prow
  OWNERS
  OWNERS_ALIASES
  charts/activiti-cloud-query/.helmignore
  charts/activiti-cloud-query/Chart.yaml
  charts/activiti-cloud-query/Makefile
  charts/activiti-cloud-query/README.md
  charts/activiti-cloud-query/templates/NOTES.txt
  charts/activiti-cloud-query/templates/_helpers.tpl
  charts/activiti-cloud-query/templates/deployment.yaml
  charts/activiti-cloud-query/templates/ingress.yaml
  charts/activiti-cloud-query/templates/service.yaml
  charts/activiti-cloud-query/values.yaml
  maven-dind.yaml
  pom.xml
  skaffold.yaml
Labels: in progress

#59 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.106
  pom.xml
Labels: in progress, updatebot

#61 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.108
  pom.xml
Labels: in progress, updatebot

#62 feat: make updatebot push cloud dependencies version for validation
  Jenkinsfile
  charts/activiti-cloud-query/Makefile
Labels: enhancement, in progress

#63 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.109
  pom.xml
Labels: updatebot

#64 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.110
  pom.xml
Labels: updatebot

#65 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.112
  pom.xml
Labels: updatebot

#66 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.113
  pom.xml
Labels: updatebot

#67 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.114
  pom.xml
Labels: updatebot

#68 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.115
  pom.xml
Labels: updatebot

#69 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.116
  pom.xml
Labels: updatebot

#70 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.117
  pom.xml
Labels: updatebot

#71 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.118
  pom.xml
Labels: updatebot

#72 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.119
  pom.xml
Labels: updatebot

#73 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.120
  pom.xml
Labels: updatebot

#74 Add missing Postgresql Chart requirements
  charts/activiti-cloud-query/requirements.yaml
Labels: bug

#75 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.121
  pom.xml
Labels: updatebot

#77 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.123
  pom.xml
Labels: updatebot

#78 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.124
  pom.xml
Labels: updatebot

#79 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.125
  pom.xml
Labels: updatebot

#80 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.126
  pom.xml
Labels: updatebot

#81 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.127
  pom.xml
Labels: updatebot

#82 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.128
  pom.xml
Labels: updatebot

#85 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.131
  pom.xml
Labels: updatebot

#86 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.132
  pom.xml
Labels: updatebot
