Repository Activiti/activiti-cloud-query, pull requests merged in 2018-11, with the labels that each got.

#43 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.75
  pom.xml
Labels: updatebot

#44 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.76
  pom.xml
Labels: updatebot

#45 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.77
  pom.xml
Labels: updatebot

#46 update org.activiti.cloud.dependencies:activiti-cloud-dependencies to 7.0.81
  pom.xml
Labels: in progress, updatebot

#48 applying activiti cloud dep upgrade to master
  pom.xml
Labels: in progress

#52 dont want bean overriding
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: in progress
